CurdMvcAll/CurdMvcAll/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CurdMvcAll.DbModels;
using CurdMvcAll.Model;
using CurdMvcAll.Repository;

namespace CurdMvcAll.Controllers
{
    public class CityController : Controller
    {
        private readonly Icity _Icity;
        public CityController(Icity City)
        {
            _Icity = City;
        }
        CityModel c = new CityModel();
        [HttpGet]
        public IActionResult AddCity(bool suss, int id)
        {
            ViewBag.SaveCityName = suss;
            c.StateModelList = _Icity.GetState();
            return View(c);
        }


        [HttpPost]
        public IActionResult AddCity(CityModel model)
        {
            if (ModelState.IsValid)
            {
                int a = _Icity.AddCity(model);
                if( a>0)
                {
                    
                    return RedirectToAction(nameof(AddCity), new { suss = true, id = model.CID });
                }
                else
                {
                    ViewBag.SaveCityName = false;
                }
            }
            c.StateModelList = _Icity.GetState();
            return View(c);
        }

        [HttpGet]
        public IActionResult GetCity()
        {
            List<CityModel> cy = _Icity.GetCity();
            return View(cy);
        }



        [HttpGet]
        public ViewResult EditCity(int id)
        {
            var editselect= _Icity.GetCityId(id);

            c.CityName = editselect.CityName;
            c.SID = editselect.SID;
            c.CID = editselect.CID;
            c.StateModelList = _Icity.GetState();
            
            
           
            if (c == null)
            {
                Response.StatusCode = 404;
                return View("home/EmployeNotfound", id);
            }
            return View(c);
        }



        [HttpPost]
        public ViewResult EditCity(CityModel model)
        {

            int a = _Icity.UpdateCity(model);
            if (a > 0)
            {
                ViewBag.update = true;
                // return RedirectToAction(nameof(State), new { suss = true, id = SM.Id });
                c.StateModelList = _Icity.GetState();
                return View("AddCity",c);
            }
            c.StateModelList = _Icity.GetState();
            return View(c);
        }

    }
}

CurdMvcAll/CurdMvcAll/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


 
<head>
    <title>Flat Able - Premium Admin Template by Phoenixcoded</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Rocker - Bootstrap4  Admin Dashboard Template</title>
    <!--favicon-->
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon">
    <!-- simplebar CSS-->
    <link href="~/assets/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
    <!-- Bootstrap core CSS-->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- animate CSS-->
    <link href="~/assets/css/animate.css" rel="stylesheet" type="text/css" />
    <!-- Icons CSS-->
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Sidebar CSS-->
    <link href="~/assets/css/sidebar-menu.css" rel="stylesheet" />
    <!-- Custom Style-->
    <link href="~/assets/css/app-style.css" rel="stylesheet" />
    <!--  datatable-->
    <link href="~/assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/plugins/bootstrap-datatable/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css">


    <link href="~/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
</head>
 
<body>
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
                <a href="index.html">
                    <img src="~/assets/images/logo-icon.png" class="logo-icon" alt="logo icon">
                    <h5 class="logo-text">RockerAdmin</h5>
                </a>
            </div>
            <ul class="sidebar-menu do-nicescrol">



                <li>
                    <a href="index.html" class="waves-effect">
                        <i class="icon-home"></i> <span>Student info</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="sidebar-submenu">
                        <li><a asp-action="Studentinfo" asp-controller="Studentinfo"><i class="fa fa-circle-o"></i>Add Student</a></li>
                        <li><a asp-action="GetAllstu" asp-controller="Studentinfo"><i class="fa fa-circle-o"></i>Student List</a></li>

                    </ul>
                </li>


                <li>
                    <a href="javaScript:void();" class="waves-effect">
                        <i class="fa fa-share"></i> <span>Master</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="sidebar-submenu">

                        <li>
                            <a href="javaScript:void();"><i class="fa fa-circle-o"></i> Add Subject <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="sidebar-submenu">
                                <li><a asp-controller="Home" asp-action="index"><i class="fa fa-circle-o"></i> Add subject</a></li>
                                <li><a asp-controller="Home" asp-action="AllSubject"><i class="fa fa-circle-o"></i> All Subject</a></li>

                            </ul>
                        </li>

                        <li>
                            <a href="javaScript:void();"><i class="fa fa-circle-o"></i>State <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="sidebar-submenu">
                                <li><a asp-controller="StateController1" asp-action="State"><i class="fa fa-circle-o"></i> Add State</a></li>
                                <li><a asp-controller="StateController1" asp-action="StateList"><i class="fa fa-circle-o"></i> All Subject</a></li>

                            </ul>
                        </li>


                        <li>
                            <a href="javaScript:void();"><i class="fa fa-circle-o"></i>City <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="sidebar-submenu">
                                <li><a asp-controller="City" asp-action="AddCity"><i class="fa fa-circle-o"></i> Add City</a></li>
                                <li><a asp-controller="City" asp-action="GetCity"><i class="fa fa-circle-o"></i> Add List</a></li>

                            </ul>
                        </li>

                    </ul>
                </li>
            </ul>

        </div>
        <!--End sidebar-wrapper-->
        <!--Start topbar header-->
        <header class="topbar-nav">
            <nav class="navbar navbar-expand fixed-top bg-white">
                <ul class="navbar-nav mr-auto align-items-center">
                    <li class="nav-item">
                        <a class="nav-link toggle-menu" href="javascript:void();">
                            <i class="icon-menu menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form class="search-bar">
                            <input type="text" class="form-control" placeholder="Enter keywords">
                            <a href="javascript:void();"><i class="icon-magnifier"></i></a>
                        </form>
                    </li>
                </ul>

                <ul class="navbar-nav align-items-center right-nav-link">

                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
                            <span class="user-profile"><img src="~/assets/images/avatars/avatar-17.png" class="img-circle" alt="user avatar"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item user-details">
                                <a href="javaScript:void();">
                                    <div class="media">
                                        <div class="avatar"><img class="align-self-start mr-3" src="~/assets/images/avatars/avatar-17.png" alt="user avatar"></div>
                                        <div class="media-body">
                                            <h6 class="mt-2 user-title">Katrina Mccoy</h6>
                                            <p class="user-subtitle">mccoy@example.com</p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-envelope mr-2"></i> Inbox</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-wallet mr-2"></i> Account</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-settings mr-2"></i> Setting</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-power mr-2"></i> Logout</li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </header>
        <!--End topbar header-->

        <div class="clearfix"></div>

        <div class="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <!-- End container-fluid-->

        </div><!--End content-wrapper-->
        <!--Start Back To Top Button-->
        <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
        <!--End Back To Top Button-->
        <!--Start footer-->
        <div class="clearfix"></div>
        <footer class="footer">
            <div class="container">
                <div class="text-center">
                    Copyright © 2020 Rocker Admin
                </div>
            </div>
        </footer>
        <!--End footer-->

    </div>


    <!-- Bootstrap core JavaScript-->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <!-- simplebar js -->
    <script src="~/assets/plugins/simplebar/js/simplebar.js"></script>
    <!-- waves effect js -->
    <script src="~/assets/js/waves.js"></script>
    <!-- sidebar-menu js -->
    <script src="~/assets/js/sidebar-menu.js"></script>
    <!-- Custom scripts -->
    <script src="~/assets/js/app-script.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <script src="~/assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js"></script>

    <script src="~/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    @await RenderSectionAsync("scriprs", required: false)
</body>


<!-- Mirrored from html.phoenixcoded.net/flatable/default/ace-editor.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 20 Feb 2021 05:21:55 GMT -->
</html>